# Generated by Django 5.0.6 on 2024-06-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('country', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apartment_number', models.CharField(max_length=10, null=True)),
                ('building_name', models.CharField(max_length=255, null=True)),
                ('street_one', models.CharField(max_length=255)),
                ('street_two', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=45)),
                ('municipality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.company')),
            ],
        ),
    ]
