# Generated by Django 5.0.6 on 2024-06-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('apartment_number', models.TextField()),
                ('building_name', models.TextField()),
                ('street_one', models.CharField(max_length=255)),
                ('street_two', models.TextField()),
                ('city', models.CharField(max_length=45)),
                ('municipality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=20)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
