# Generated by Django 5.0.6 on 2024-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_alter_property_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
