# Generated by Django 5.0.6 on 2024-06-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_remove_property_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homestay.company'),
            preserve_default=False,
        ),
    ]
